# Generated by Django 4.1.3 on 2023-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HIL', 'Хилы'), ('DD', 'ДД'), ('MER', 'Торговцы'), ('GLD', 'Гилдмастеры'), ('QST', 'Квестгиверы'), ('SMT', 'Кузнецы'), ('TNR', 'Кожевники'), ('PTN', 'Зельевары'), ('SPL', 'Мастера заклинаний')], default='', max_length=3),
        ),
    ]
