# Generated by Django 4.1.3 on 2023-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comments_approved_comments_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='approved_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='deleted_notice',
            field=models.BooleanField(default=False),
        ),
    ]
