# Generated by Django 4.1.3 on 2023-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comments_approved_notice_comments_deleted_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
